import Head from 'next/head'
import Image from 'next/image'
import Category from '../components/Category'
import Chef from '../components/Chef'
import Featured from '../components/Featured'
import Offer from '../components/Offer'
import Product from '../components/Product'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured/>
      <Category/>
      <Chef/>
      <Offer/>
    </div>
  )
}


